
MODEL: '6D'
DEBUG: False

TRAINING:
  NUM_GPUS: [1]
  #BATCH_SIZE: 24 # BS for each dataloader (in every GPU)
  BATCH_SIZE: 16
  #NUM_WORKERS: 8
  NUM_WORKERS: 16
  SAMPLER: 'scene_balance'
  N_SAMPLES_SCENE: 100 #100c
  SAMPLE_WITH_REPLACEMENT: Tru

  LR:  1e-4  #1e-5
  WEIGHT_DECAY: 5e-4

  LR_GAMMA: 0.5       # 学习率缩放因子
  LR_PATIENCE: 100   # 忍受多少 epoch 验证损失不下降

  LR_STEP_INTERVAL: 100
  LR_STEP_GAMMA: 0.5

  LOG_INTERVAL: 50
  VAL_INTERVAL: 0.5
#  VAL_BATCHES: 100
  VAL_BATCHES: 100
  EPOCHS: 20

DATASET:
#  HEIGHT: 480
#  WIDTH: 360
  HEIGHT: 240
  WIDTH: 240

  MIN_OVERLAP_SCORE: 0.0  # [train only] discard data with overlap_score < min_overlap_score
  MAX_OVERLAP_SCORE: 1.0  # [train only] discard data with overlap_score < min_overlap_score

#LOSS_CLASS:
#
#  LOSS_FUNCTION: "VCRE" # VCRE or POSE_ERR
#  #SOFT_CLIPPING: True # It indicates if it soft-clips the loss values.
#  SOFT_CLIPPING: True # It indicates if it soft-clips the loss values.
#  MASK_LOSS_WEIGHT: 3  #1
#  POSE_ERR:
#    MAX_LOSS_VALUE: 1.5
#    MAX_LOSS_SOFTVALUE: 0.8
#  VCRE:
#    MAX_LOSS_VALUE: 90
#    MAX_LOSS_SOFTVALUE: 0.8
#
#  GENERATE_HYPOTHESES:
#    SCORE_TEMPERATURE: 20
##    IT_MATCHES: 20
#    IT_MATCHES: 20
#    IT_RANSAC: 20
##    INLIER_3D_TH: 0.3
##    INLIER_REF_TH: 0.15
#    INLIER_3D_TH: 0.3
#    INLIER_REF_TH: 0.15
#    NUM_REF_STEPS: 4
#    NUM_CORR_3d3d: 8 # Bigger number of 3d-3d correspondences helps stability
#
#  NULL_HYPOTHESIS:
#    ADD_NULL_HYPOTHESIS: False
#    TH_OUTLIERS: 0.35
#
#  CURRICULUM_LEARNING:
#    TRAIN_CURRICULUM: True # It indicates if MicKey should be trained with curriculum learning
#    TRAIN_WITH_TOPK: False # It indicates if MicKey should be trained only with top image pairs
#    TOPK_INIT: 30 #30
#    TOPK: 80 #80
#
#  SAMPLER:
#    NUM_SAMPLES_MATCHES: 64 #64
#
#PROCRUSTES:
#  IT_MATCHES: 20 #20  #20
#  IT_RANSAC: 100   #100
#  NUM_SAMPLED_MATCHES: 2048 # 2048 #2048
#  NUM_CORR_3D_3D: 3
##  NUM_SAMPLED_MATCHES: 8192 # 2048 #2048
##  NUM_CORR_3D_3D: 12
#
#  NUM_REFINEMENTS: 4
#  #TH_INLIER: 0.15
#  TH_INLIER: 0.15
#  #TH_SOFT_INLIER: 0.3
#  TH_SOFT_INLIER: 0.3
#
##o
#loss:
#  pos_margin: 0.2
#  neg_margin: 0.9
#  neg_kernel_size: 5
#  hard_negatives: True
#  mask_type: 'dice'  # 或其他支持的损失类型
#test:
#  mask_threshold: 0.5
