
MODEL: '6D'
DEBUG: False

TRAINING:
  NUM_GPUS: 2
  #BATCH_SIZE: 24 # BS for each dataloader (in every GPU)
  BATCH_SIZE: 32
  #NUM_WORKERS: 8
  NUM_WORKERS: 2
  SAMPLER: 'scene_balance'
  N_SAMPLES_SCENE: 100 #100c
  SAMPLE_WITH_REPLACEMENT: Tru

  LR:  1e-3  #1e-5

  WEIGHT_DECAY: 5e-4

  LR_GAMMA: 0.5       # 学习率缩放因子
  LR_PATIENCE: 100   # 忍受多少 epoch 验证损失不下降

  LR_STEP_INTERVAL: 100
  LR_STEP_GAMMA: 0.5

  LOG_INTERVAL: 50
  VAL_INTERVAL: 0.5
#  VAL_BATCHES: 100
  VAL_BATCHES: 100
  EPOCHS: 20

