from yacs.config import CfgNode as CN

_CN = CN()

############## MicKey 配置 ##############
_CN.MODEL = None
_CN.DEBUG = False

_CN.model = CN()
_CN.model.use_catseg_ckpt = True

_CN.model.image_encoder = CN()
_CN.model.image_encoder.img_size = [192, 192]
_CN.model.image_encoder.out_channels = 1024
_CN.model.image_encoder.extra_upsampling = True
_CN.model.image_encoder.vlm = "clip"
_CN.model.image_encoder.use_decoder_guidance = True
_CN.model.image_encoder.use_cost_guidance = True
_CN.model.image_encoder.decoder_type = "standard"

############# TRAINING (MicKey) #############
_CN.TRAINING = CN()
_CN.TRAINING.BATCH_SIZE = None
_CN.TRAINING.NUM_WORKERS = None
_CN.TRAINING.NUM_GPUS = None
_CN.TRAINING.SAMPLER = None
_CN.TRAINING.N_SAMPLES_SCENE = None
_CN.TRAINING.SAMPLE_WITH_REPLACEMENT = None
_CN.TRAINING.LR = None
_CN.TRAINING.WEIGHT_DECAY = None
_CN.TRAINING.LR_GAMMA = None
_CN.TRAINING.LR_PATIENCE = None
_CN.TRAINING.LR_STEP_INTERVAL = None
_CN.TRAINING.LR_STEP_GAMMA = None
_CN.TRAINING.VAL_INTERVAL = None
_CN.TRAINING.VAL_BATCHES = None
_CN.TRAINING.LOG_INTERVAL = None
_CN.TRAINING.EPOCHS = None
_CN.TRAINING.GRAD_CLIP = 0.

############## DATASET (MicKey) ##############
_CN.DATASET = CN()
_CN.DATASET.DATA_SOURCE = None
_CN.DATASET.SCENES = None
_CN.DATASET.DATA_ROOT = None
_CN.DATASET.SEED = None
_CN.DATASET.NPZ_ROOT = None
_CN.DATASET.MIN_OVERLAP_SCORE = None
_CN.DATASET.MAX_OVERLAP_SCORE = None
_CN.DATASET.CONSECUTIVE_PAIRS = None
_CN.DATASET.FRAME_RATE = None
_CN.DATASET.AUGMENTATION_TYPE = None
_CN.DATASET.BLACK_WHITE = False
_CN.DATASET.PAIRS_TXT = CN()
_CN.DATASET.PAIRS_TXT.TRAIN = None
_CN.DATASET.PAIRS_TXT.VAL = None
_CN.DATASET.PAIRS_TXT.TEST = None
_CN.DATASET.PAIRS_TXT.ONE_NN = False
_CN.DATASET.HEIGHT = None
_CN.DATASET.WIDTH = None


############## LoFTR 配置 ##############
_CN.LOFTR = CN()
_CN.LOFTR.BACKBONE_TYPE = 'ResNetFPN'
_CN.LOFTR.RESOLUTION = (8, 2)
_CN.LOFTR.FINE_WINDOW_SIZE = 5
_CN.LOFTR.FINE_CONCAT_COARSE_FEAT = True

_CN.LOFTR.RESNETFPN = CN()
_CN.LOFTR.RESNETFPN.INITIAL_DIM = 128
_CN.LOFTR.RESNETFPN.BLOCK_DIMS = [128, 196, 256]

_CN.LOFTR.COARSE = CN()
_CN.LOFTR.COARSE.D_MODEL = 256
_CN.LOFTR.COARSE.D_FFN = 256
_CN.LOFTR.COARSE.NHEAD = 8
_CN.LOFTR.COARSE.LAYER_NAMES = ['self', 'cross'] * 4
_CN.LOFTR.COARSE.ATTENTION = 'linear'
_CN.LOFTR.COARSE.TEMP_BUG_FIX = True

_CN.LOFTR.MATCH_COARSE = CN()
_CN.LOFTR.MATCH_COARSE.THR = 0.2
_CN.LOFTR.MATCH_COARSE.BORDER_RM = 2
_CN.LOFTR.MATCH_COARSE.MATCH_TYPE = 'dual_softmax'
_CN.LOFTR.MATCH_COARSE.DSMAX_TEMPERATURE = 0.1
_CN.LOFTR.MATCH_COARSE.SKH_ITERS = 3
_CN.LOFTR.MATCH_COARSE.SKH_INIT_BIN_SCORE = 1.0
_CN.LOFTR.MATCH_COARSE.SKH_PREFILTER = False
_CN.LOFTR.MATCH_COARSE.TRAIN_COARSE_PERCENT = 0.2
#_CN.LOFTR.MATCH_COARSE.TRAIN_PAD_NUM_GT_MIN = 200
_CN.LOFTR.MATCH_COARSE.TRAIN_PAD_NUM_GT_MIN = 50
_CN.LOFTR.MATCH_COARSE.SPARSE_SPVS = True

_CN.LOFTR.FINE = CN()
_CN.LOFTR.FINE.D_MODEL = 128
_CN.LOFTR.FINE.D_FFN = 128
_CN.LOFTR.FINE.NHEAD = 8
_CN.LOFTR.FINE.LAYER_NAMES = ['self', 'cross'] * 1
_CN.LOFTR.FINE.ATTENTION = 'linear'

# LoFTR Loss
_CN.LOFTR.LOSS = CN()
_CN.LOFTR.LOSS.COARSE_TYPE = 'focal'
_CN.LOFTR.LOSS.COARSE_WEIGHT = 1.0
_CN.LOFTR.LOSS.FOCAL_ALPHA = 0.25
_CN.LOFTR.LOSS.FOCAL_GAMMA = 2.0
_CN.LOFTR.LOSS.POS_WEIGHT = 1.0
_CN.LOFTR.LOSS.NEG_WEIGHT = 1.0
_CN.LOFTR.LOSS.FINE_TYPE = 'l2_with_std'
_CN.LOFTR.LOSS.FINE_WEIGHT = 1.0
_CN.LOFTR.LOSS.FINE_CORRECT_THR = 1.0


############## LoFTR DATASET 配置 ##############
_CN.LOFTR_DATASET = CN()
_CN.LOFTR_DATASET.TRAINVAL_DATA_SOURCE = None
_CN.LOFTR_DATASET.TRAIN_DATA_ROOT = None
_CN.LOFTR_DATASET.TRAIN_POSE_ROOT = None
_CN.LOFTR_DATASET.TRAIN_NPZ_ROOT = None
_CN.LOFTR_DATASET.TRAIN_LIST_PATH = None
_CN.LOFTR_DATASET.TRAIN_INTRINSIC_PATH = None
_CN.LOFTR_DATASET.VAL_DATA_ROOT = None
_CN.LOFTR_DATASET.VAL_POSE_ROOT = None
_CN.LOFTR_DATASET.VAL_NPZ_ROOT = None
_CN.LOFTR_DATASET.VAL_LIST_PATH = None
_CN.LOFTR_DATASET.VAL_INTRINSIC_PATH = None
_CN.LOFTR_DATASET.TEST_DATA_SOURCE = None
_CN.LOFTR_DATASET.TEST_DATA_ROOT = None
_CN.LOFTR_DATASET.TEST_POSE_ROOT = None
_CN.LOFTR_DATASET.TEST_NPZ_ROOT = None
_CN.LOFTR_DATASET.TEST_LIST_PATH = None
_CN.LOFTR_DATASET.TEST_INTRINSIC_PATH = None
_CN.LOFTR_DATASET.MIN_OVERLAP_SCORE_TRAIN = 0.4
_CN.LOFTR_DATASET.MIN_OVERLAP_SCORE_TEST = 0.0
_CN.LOFTR_DATASET.AUGMENTATION_TYPE = None
_CN.LOFTR_DATASET.MGDPT_IMG_RESIZE = 640
_CN.LOFTR_DATASET.MGDPT_IMG_PAD = True
_CN.LOFTR_DATASET.MGDPT_DEPTH_PAD = True
_CN.LOFTR_DATASET.MGDPT_DF = 8


############## TRAINER (LoFTR) ##############
_CN.TRAINER = CN()
_CN.TRAINER.WORLD_SIZE = 1
_CN.TRAINER.CANONICAL_BS = 64
_CN.TRAINER.CANONICAL_LR = 6e-3
_CN.TRAINER.SCALING = None
_CN.TRAINER.FIND_LR = False
_CN.TRAINER.OPTIMIZER = "adamw"
_CN.TRAINER.TRUE_LR = None
_CN.TRAINER.ADAM_DECAY = 0.
_CN.TRAINER.ADAMW_DECAY = 0.1
_CN.TRAINER.WARMUP_TYPE = 'linear'
_CN.TRAINER.WARMUP_RATIO = 0.
_CN.TRAINER.WARMUP_STEP = 4800
_CN.TRAINER.SCHEDULER = 'MultiStepLR'
_CN.TRAINER.SCHEDULER_INTERVAL = 'epoch'
_CN.TRAINER.MSLR_MILESTONES = [3, 6, 9, 12]
_CN.TRAINER.MSLR_GAMMA = 0.5
_CN.TRAINER.COSA_TMAX = 30
_CN.TRAINER.ELR_GAMMA = 0.999992
_CN.TRAINER.ENABLE_PLOTTING = True
_CN.TRAINER.N_VAL_PAIRS_TO_PLOT = 32
_CN.TRAINER.PLOT_MODE = 'evaluation'
_CN.TRAINER.PLOT_MATCHES_ALPHA = 'dynamic'
_CN.TRAINER.EPI_ERR_THR = 5e-4
_CN.TRAINER.POSE_GEO_MODEL = 'E'
_CN.TRAINER.POSE_ESTIMATION_METHOD = 'RANSAC'
_CN.TRAINER.RANSAC_PIXEL_THR = 0.5
_CN.TRAINER.RANSAC_CONF = 0.99999
_CN.TRAINER.RANSAC_MAX_ITERS = 10000
_CN.TRAINER.USE_MAGSACPP = False
_CN.TRAINER.DATA_SAMPLER = 'scene_balance'
_CN.TRAINER.N_SAMPLES_PER_SUBSET = 200
_CN.TRAINER.SB_SUBSET_SAMPLE_REPLACEMENT = True
_CN.TRAINER.SB_SUBSET_SHUFFLE = True
_CN.TRAINER.SB_REPEAT = 1
_CN.TRAINER.RDM_REPLACEMENT = True
_CN.TRAINER.RDM_NUM_SAMPLES = None
_CN.TRAINER.GRADIENT_CLIPPING = 0.5
_CN.TRAINER.SEED = 66
cfg = _CN

def get_cfg_defaults():
    return _CN.clone()
