DATA:
  BOX_SCALE: 5.0
  KEEP_RATIO: false
  NORMALIZED_DEPTH: true
  RANDOM_BOX_OFFSET: null
  RANDOM_BOX_SCALE: null
INPUT:
  DEPTH: true
  NORMAL: false
MODEL:
  DEPTH: 18
  DROPOUT: 0.0
  EMBED_DIM: 1024
  FREEZE_AT: 0
  FREEZE_BN: true
  GLOBAL_POOL_TYPE: Max
  LARGE_FC: false
  NORMALIZE_EMBED: false
SEED: 20
SOLVER:
  BACKUP_PERIOD: 5000
  BAD_EVALS_TO_DECAY: 2
  BATCH_SIZE: 8
  EVAL_PERIOD: 5000
  LOG_PERIOD: 50
  LOSS:
    FOCAL_POW: 2.0
    MARGIN: 1.0
    NAME: triplet
  MAX_ITERS: 100000
  OPTIM:
    LR: 0.0001
    MOMENTUM: 0.9
    NAME: SGD
    WDECAY: 0.001
  VAL_STEP: true
  VAL_STEP_PERIOD: 5
  WORKERS: 4
